[pytest]
addopts = -p no:hydra_pytest -p no:gltest
testpaths = tests/direct
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
    ignore::RuntimeWarning
